using System.Linq;
using EulerLib;

namespace Euler.Problems
{
    public class Problem2 : IProblem
    {
        public string Title => "Even Fibonacci numbers";

        public string Description => @"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
";

        public string GetSolution()
        {
            return Fibonacci.Sequence()
                .TakeWhile(f => f < 4000000)
                .Where(n => n % 2 == 0)
                .Sum()
                .ToString();
        }
    }
}
